USE [master]
GO

/****** Object:  Database [n5mpleados]    Script Date: 8/02/2024 8:38:53 p. m. ******/
CREATE DATABASE [n5mpleados]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'n5mpleados', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\n5mpleados.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'n5mpleados_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\n5mpleados_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [n5mpleados].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [n5mpleados] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [n5mpleados] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [n5mpleados] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [n5mpleados] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [n5mpleados] SET ARITHABORT OFF 
GO

ALTER DATABASE [n5mpleados] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [n5mpleados] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [n5mpleados] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [n5mpleados] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [n5mpleados] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [n5mpleados] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [n5mpleados] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [n5mpleados] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [n5mpleados] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [n5mpleados] SET  DISABLE_BROKER 
GO

ALTER DATABASE [n5mpleados] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [n5mpleados] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [n5mpleados] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [n5mpleados] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [n5mpleados] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [n5mpleados] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [n5mpleados] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [n5mpleados] SET RECOVERY FULL 
GO

ALTER DATABASE [n5mpleados] SET  MULTI_USER 
GO

ALTER DATABASE [n5mpleados] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [n5mpleados] SET DB_CHAINING OFF 
GO

ALTER DATABASE [n5mpleados] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [n5mpleados] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [n5mpleados] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [n5mpleados] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [n5mpleados] SET QUERY_STORE = OFF
GO

ALTER DATABASE [n5mpleados] SET  READ_WRITE 
GO


